#!/usr/bin/env python3
# This directory is synchronized with a remote branch or repository.
# Use './git-sublib pull' to incorporate new changes from the remote.
import sys

REMOTE_TYPE = 'branch'
REMOTE_BRANCH = 'lib_1'
REMOTE_LAST_MERGED_COMMIT = '021e48690531edec5c9ac2b24cad2337a85836c1'
LOCAL_LAST_MERGE_PARENT = 'b2e4b0c6c041a09b838cc179bb55136266172ddc'

USAGE = """
USAGE
"""


def main():
    if len(sys.argv) < 2:
        print(USAGE)
        return

    command = sys.argv[1]
    print(f'Command: {command}')

    if command == 'pull':
        print("PULLING")


if __name__ == '__main__':
    main()
